---
# tasks file for rpsetup:bind

- name: BIND - Install/Update apt package
  package:
    name: "{{item}}"
    state: present
  with_items: "{{package_install}}"
  when: inventory_hostname in groups['bind']


- name: BIND - Enable Service
  service:
    name: "{{bind_service}}"
    enabled: yes
  when: inventory_hostname in groups['bind']


- name: BIND - Create conf.local file from a template
  template:
    src: etc/bind/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: 0644
  notify: BIND Restart
  when: inventory_hostname in groups['bind']


- name: BIND - Create conf.options file from a template
  template:
    src: etc/bind/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: 0644
  notify: BIND Restart
  when: inventory_hostname in groups['bind']

- name: BIND - Create zones directory
  file:
    path: "/etc/bind/zones"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname in groups['bind']

- name: BIND - Deploy new test files to root home
  template:
    src: etc/bind/zones/db.zone.j2
    dest: "/etc/bind/zones/db.{{dns_zone}}"
    owner: root
    group: root
    mode: 0644
  notify: BIND Restart
  when: inventory_hostname in groups['bind']

- name: BIND - Deploy new test files to root home
  template:
    src: etc/bind/zones/db.reverse.j2
    dest: /etc/bind/zones/db.reverse
    owner: root
    group: root
    mode: 0644
  notify: BIND Restart
  when: inventory_hostname in groups['bind']